### ISSUE TITLE
Spaces in filenames

### ISSUE THREAD

**Issue by phall-brown** [2tommyfrank/eeps1400-labs#1]
Filenames with spaces in them can be cumbersome and inconvenient to deal with from the command line in Linux. Would it be possible to eliminate spaces from filenames? For example, use Lab1.ipynb instead of Lab 1.ipynb.

**Comment by 2tommyfrank** [comment]
Fixed. I also split the notebook into weeks since each week can be run independently, so we can make changes to later weeks if necessary.
